package main
import("bufio";"bytes";"compress/gzip";"encoding/binary";"hash/crc32";"io";"os";"path/filepath";"strings";"sync";"testing")
func TestRESP(t *testing.T){var b bytes.Buffer;_ = command(&b,"message","c",`{"p":"0.1000"}`);v,e:=resp(bufio.NewReader(&b),0);if e!=nil{t.Fatal(e)};a:=v.([]any);if len(a)!=3||bulkString(a[0])!="message"{t.Fatal(v)}}
func TestRESPBad(t *testing.T){for _,s:=range []string{"\r\n","$-2\r\n","$999999999\r\n","*999999\r\n","$2\r\nAAzz","?x\r\n",strings.Repeat("x",5000)+"\n"}{if _,e:=resp(bufio.NewReader(strings.NewReader(s)),0);e==nil{t.Fatal("accepted invalid RESP")}}}
func readWAL(t *testing.T,path string)[][]byte{t.Helper();f,e:=os.Open(path);if e!=nil{t.Fatal(e)};defer f.Close();z,e:=gzip.NewReader(f);if e!=nil{t.Fatal(e)};defer z.Close();b,e:=io.ReadAll(z);if e!=nil{t.Fatal(e)};if string(b[:4])!="PDW1"{t.Fatal("magic")};b=b[4:];var got [][]byte
for len(b)>0{n:=int(binary.BigEndian.Uint32(b));h,p:=b[:24],b[24:24+n];c:=crc32.NewIEEE();c.Write(h[8:]);c.Write(p);if c.Sum32()!=binary.BigEndian.Uint32(h[4:]){t.Fatal("crc")};got=append(got,append([]byte(nil),p...));b=b[24+n:]};return got}
func TestWAL(t *testing.T){t.Setenv("DISK_RESERVE_BYTES","0");root:=t.TempDir();r,e:=newRecorder(root,"raw");if e!=nil{t.Fatal(e)};p:=[]byte(`{"p":"0.1000"}`);if e=r.append(p);e!=nil{t.Fatal(e)};if e=r.checkpoint();e!=nil{t.Fatal(e)};if r.received!=1||r.durable!=1{t.Fatal("counter")};if e=r.close();e!=nil{t.Fatal(e)};paths,_:=filepath.Glob(filepath.Join(root,"spool/raw/*.ready"));got:=readWAL(t,paths[0]);if !bytes.Equal(got[len(got)-1],p){t.Fatal("bytes")}}
func TestLock(t *testing.T){t.Setenv("DISK_RESERVE_BYTES","0");root:=t.TempDir();r,e:=newRecorder(root,"raw");if e!=nil{t.Fatal(e)};defer r.close();if r2,e:=newRecorder(root,"raw");e==nil{r2.close();t.Fatal("duplicate writer")}}
func TestDiskReserve(t *testing.T){t.Setenv("DISK_RESERVE_BYTES","0");r,e:=newRecorder(t.TempDir(),"raw");if e!=nil{t.Fatal(e)};defer r.close();r.floor=^uint64(0);if e=r.checkpoint();e!=nil{t.Fatal(e)};if e=r.append([]byte("x"));e!=errDisk{t.Fatal(e)};if r.received!=1||r.appended!=0{t.Fatal("hidden drop")}}
func TestConcurrentCheckpoint(t *testing.T){t.Setenv("DISK_RESERVE_BYTES","0");r,e:=newRecorder(t.TempDir(),"raw");if e!=nil{t.Fatal(e)};defer r.close();var wg sync.WaitGroup;wg.Add(2);go func(){defer wg.Done();for i:=0;i<500;i++{if e:=r.append([]byte("x"));e!=nil{t.Error(e)}}}();go func(){defer wg.Done();for i:=0;i<20;i++{if e:=r.checkpoint();e!=nil{t.Error(e)}}}();wg.Wait();if e=r.checkpoint();e!=nil{t.Fatal(e)};if r.durable!=500{t.Fatal(r.durable)}}
func TestOrphanRecovery(t *testing.T){t.Setenv("DISK_RESERVE_BYTES","0");root:=t.TempDir();p:=filepath.Join(root,"spool/raw/old.open");os.MkdirAll(filepath.Dir(p),0700);os.WriteFile(p,[]byte("broken gzip"),0600);r,e:=newRecorder(root,"raw");if e!=nil{t.Fatal(e)};defer r.close();if _,e=os.Stat(strings.TrimSuffix(p,".open")+".recovered");e!=nil{t.Fatal(e)}}
func BenchmarkSpool(b *testing.B){b.Setenv("DISK_RESERVE_BYTES","0");r,e:=newRecorder(b.TempDir(),"raw");if e!=nil{b.Fatal(e)};defer r.close();p:=[]byte(`{"event_type":"price_change","market":"0x1","asset_id":"123456","timestamp":"1791331200000","price":"0.543","size":"42.123","side":"BUY","best_bid":"0.543","best_ask":"0.544","hash":"test123456"}`);b.SetBytes(int64(len(p)));b.ResetTimer();for i:=0;i<b.N;i++{if e=r.append(p);e!=nil{b.Fatal(e)}}}
